In [1]:
import pandas as pd
import networkx as nx
import numpy as np
import glob

import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

# for notebook
%matplotlib inline

## Datasets

englishfootball : 123 temporadas

In [2]:
# https://github.com/jfjelstul/englishfootball

englishfootball = pd.read_csv('../data/englishfootball/data-csv/matches.csv', sep=',')
df = englishfootball.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203956 entries, 0 to 203955
Data columns (total 21 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   key_id                  203956 non-null  int64
 1   season_id               203956 non-null  object
 2   season                  203956 non-null  int64
 3   tier                    203956 non-null  int64
 4   division                203956 non-null  object
 5   subdivision             203956 non-null  object
 6   match_id                203956 non-null  object
 7   match_name              203956 non-null  object
 8   home_team_id            203956 non-null  object
 9   home_team_name          203956 non-null  object
 10  away_team_id            203956 non-null  object
 11  away_team_name          203956 non-null  object
 12  score                   203956 non-null  object
 13  home_team_score         203956 non-null  int64
 14  away_team_score         203956 non-null  int64
 15  home_team_score_margin  203956 non-null  int64
 16  away_team_score_margin  203956 non-null  int64
 17  result                  203956 non-null  object
 18  home_team_win           203956 non-null  int64
 19  away_team_win           203956 non-null  int64
 20  draw                    203956 non-null  int64
dtypes: int64(10), object(11)
memory usage: 32.7+ MB

In [3]:
df.head(20)

,key_id,season_id,season,tier,division,subdivision,match_id,match_name,home_team_id,home_team_name,...,away_team_name,score,home_team_score,away_team_score,home_team_score_margin,away_team_score_margin,result,home_team_win,away_team_win,draw
0,1,S-1888-1,1888,1,First Division,None,M-1888-1-001,Accrington vs Aston Villa,T-001,Accrington,...,Aston Villa,1-1,1,1,0,0,draw,0,0,1
1,2,S-1888-1,1888,1,First Division,None,M-1888-1-002,Accrington vs Blackburn Rovers,T-001,Accrington,...,Blackburn Rovers,0-2,0,2,-2,2,away team win,0,1,0
2,3,S-1888-1,1888,1,First Division,None,M-1888-1-003,Accrington vs Bolton Wanderers,T-001,Accrington,...,Bolton Wanderers,2-3,2,3,-1,1,away team win,0,1,0
3,4,S-1888-1,1888,1,First Division,None,M-1888-1-004,Accrington vs Burnley,T-001,Accrington,...,Burnley,5-1,5,1,4,-4,home team win,1,0,0
4,5,S-1888-1,1888,1,First Division,None,M-1888-1-005,Accrington vs Derby County,T-001,Accrington,...,Derby County,6-2,6,2,4,-4,home team win,1,0,0
5,6,S-1888-1,1888,1,First Division,None,M-1888-1-006,Accrington vs Everton,T-001,Accrington,...,Everton,3-1,3,1,2,-2,home team win,1,0,0
6,7,S-1888-1,1888,1,First Division,None,M-1888-1-007,Accrington vs Notts County,T-001,Accrington,...,Notts County,1-2,1,2,-1,1,away team win,0,1,0
7,8,S-1888-1,1888,1,First Division,None,M-1888-1-008,Accrington vs Preston North End,T-001,Accrington,...,Preston North End,0-0,0,0,0,0,draw,0,0,1
8,9,S-1888-1,1888,1,First Division,None,M-1888-1-009,Accrington vs Stoke,T-001,Accrington,...,Stoke,2-0,2,0,2,-2,home team win,1,0,0
9,10,S-1888-1,1888,1,First Division,None,M-1888-1-010,Accrington vs West Bromwich Albion,T-001,Accrington,...,West Bromwich Albion,2-1,2,1,1,-1,home team win,1,0,0
10,11,S-1888-1,1888,1,First Division,None,M-1888-1-011,Accrington vs Wolverhampton Wanderers,T-001,Accrington,...,Wolverhampton Wanderers,4-4,4,4,0,0,draw,0,0,1
11,12,S-1888-1,1888,1,First Division,None,M-1888-1-012,Aston Villa vs Accrington,T-002,Aston Villa,...,Accrington,4-3,4,3,1,-1,home team win,1,0,0
12,13,S-1888-1,1888,1,First Division,None,M-1888-1-013,Aston Villa vs Blackburn Rovers,T-002,Aston Villa,...,Blackburn Rovers,6-1,6,1,5,-5,home team win,1,0,0
13,14,S-1888-1,1888,1,First Division,None,M-1888-1-014,Aston Villa vs Bolton Wanderers,T-002,Aston Villa,...,Bolton Wanderers,6-2,6,2,4,-4,home team win,1,0,0
14,15,S-1888-1,1888,1,First Division,None,M-1888-1-015,Aston Villa vs Burnley,T-002,Aston Villa,...,Burnley,4-2,4,2,2,-2,home team win,1,0,0
15,16,S-1888-1,1888,1,First Division,None,M-1888-1-016,Aston Villa vs Derby County,T-002,Aston Villa,...,Derby County,4-2,4,2,2,-2,home team win,1,0,0
16,17,S-1888-1,1888,1,First Division,None,M-1888-1-017,Aston Villa vs Everton,T-002,Aston Villa,...,Everton,2-1,2,1,1,-1,home team win,1,0,0
17,18,S-1888-1,1888,1,First Division,None,M-1888-1-018,Aston Villa vs Notts County,T-002,Aston Villa,...,Notts County,9-1,9,1,8,-8,home team win,1,0,0
18,19,S-1888-1,1888,1,First Division,None,M-1888-1-019,Aston Villa vs Preston North End,T-002,Aston Villa,...,Preston North End,0-2,0,2,-2,2,away team win,0,1,0
19,20,S-1888-1,1888,1,First Division,None,M-1888-1-020,Aston Villa vs Stoke,T-002,Aston Villa,...,Stoke,5-1,5,1,4,-4,home team win,1,0,0

In [4]:
df.tail(20)

,key_id,season_id,season,tier,division,subdivision,match_id,match_name,home_team_id,home_team_name,...,away_team_name,score,home_team_score,away_team_score,home_team_score_margin,away_team_score_margin,result,home_team_win,away_team_win,draw
203936,203937,S-2021-4,2021,4,League Two,None,M-2021-4-533,Walsall vs Carlisle United,T-028,Walsall,...,Carlisle United,1-0,1,0,1,-1,home team win,1,0,0
203937,203938,S-2021-4,2021,4,League Two,None,M-2021-4-534,Walsall vs Colchester United,T-028,Walsall,...,Colchester United,3-0,3,0,3,-3,home team win,1,0,0
203938,203939,S-2021-4,2021,4,League Two,None,M-2021-4-535,Walsall vs Crawley Town,T-028,Walsall,...,Crawley Town,1-1,1,1,0,0,draw,0,0,1
203939,203940,S-2021-4,2021,4,League Two,None,M-2021-4-536,Walsall vs Exeter City,T-028,Walsall,...,Exeter City,0-2,0,2,-2,2,away team win,0,1,0
203940,203941,S-2021-4,2021,4,League Two,None,M-2021-4-537,Walsall vs Forest Green Rovers,T-028,Walsall,...,Forest Green Rovers,1-3,1,3,-2,2,away team win,0,1,0
203941,203942,S-2021-4,2021,4,League Two,None,M-2021-4-538,Walsall vs Harrogate Town,T-028,Walsall,...,Harrogate Town,1-3,1,3,-2,2,away team win,0,1,0
203942,203943,S-2021-4,2021,4,League Two,None,M-2021-4-539,Walsall vs Hartlepool United,T-028,Walsall,...,Hartlepool United,3-1,3,1,2,-2,home team win,1,0,0
203943,203944,S-2021-4,2021,4,League Two,None,M-2021-4-540,Walsall vs Leyton Orient,T-028,Walsall,...,Leyton Orient,0-2,0,2,-2,2,away team win,0,1,0
203944,203945,S-2021-4,2021,4,League Two,None,M-2021-4-541,Walsall vs Mansfield Town,T-028,Walsall,...,Mansfield Town,3-1,3,1,2,-2,home team win,1,0,0
203945,203946,S-2021-4,2021,4,League Two,None,M-2021-4-542,Walsall vs Newport County,T-028,Walsall,...,Newport County,3-3,3,3,0,0,draw,0,0,1
203946,203947,S-2021-4,2021,4,League Two,None,M-2021-4-543,Walsall vs Northampton Town,T-028,Walsall,...,Northampton Town,0-1,0,1,-1,1,away team win,0,1,0
203947,203948,S-2021-4,2021,4,League Two,None,M-2021-4-544,Walsall vs Oldham Athletic,T-028,Walsall,...,Oldham Athletic,2-1,2,1,1,-1,home team win,1,0,0
203948,203949,S-2021-4,2021,4,League Two,None,M-2021-4-545,Walsall vs Port Vale,T-028,Walsall,...,Port Vale,2-0,2,0,2,-2,home team win,1,0,0
203949,203950,S-2021-4,2021,4,League Two,None,M-2021-4-546,Walsall vs Rochdale,T-028,Walsall,...,Rochdale,0-0,0,0,0,0,draw,0,0,1
203950,203951,S-2021-4,2021,4,League Two,None,M-2021-4-547,Walsall vs Salford City,T-028,Walsall,...,Salford City,2-1,2,1,1,-1,home team win,1,0,0
203951,203952,S-2021-4,2021,4,League Two,None,M-2021-4-548,Walsall vs Scunthorpe United,T-028,Walsall,...,Scunthorpe United,1-1,1,1,0,0,draw,0,0,1
203952,203953,S-2021-4,2021,4,League Two,None,M-2021-4-549,Walsall vs Stevenage,T-028,Walsall,...,Stevenage,1-0,1,0,1,-1,home team win,1,0,0
203953,203954,S-2021-4,2021,4,League Two,None,M-2021-4-550,Walsall vs Sutton United,T-028,Walsall,...,Sutton United,1-0,1,0,1,-1,home team win,1,0,0
203954,203955,S-2021-4,2021,4,League Two,None,M-2021-4-551,Walsall vs Swindon Town,T-028,Walsall,...,Swindon Town,0-3,0,3,-3,3,away team win,0,1,0
203955,203956,S-2021-4,2021,4,League Two,None,M-2021-4-552,Walsall vs Tranmere Rovers,T-028,Walsall,...,Tranmere Rovers,1-0,1,0,1,-1,home team win,1,0,0

In [5]:
df.columns

Index(['key_id', 'season_id', 'season', 'tier', 'division', 'subdivision',
       'match_id', 'match_name', 'home_team_id', 'home_team_name',
       'away_team_id', 'away_team_name', 'score', 'home_team_score',
       'away_team_score', 'home_team_score_margin', 'away_team_score_margin',
       'result', 'home_team_win', 'away_team_win', 'draw'],
      dtype='object')

In [6]:
df = df[[
    'season', 
    'home_team_name', 
    'away_team_name', 
    'home_team_score', 
    'away_team_score']
    ] 

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203956 entries, 0 to 203955
Data columns (total 5 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   season           203956 non-null  int64
 1   home_team_name   203956 non-null  object
 2   away_team_name   203956 non-null  object
 3   home_team_score  203956 non-null  int64
 4   away_team_score  203956 non-null  int64
dtypes: int64(3), object(2)
memory usage: 7.8+ MB

In [7]:
df.rename(columns = {
    'season':'year', 
    'home_team_name':'home', 
    'away_team_name':'away', 
    'home_team_score':'home_goals', 
    'away_team_score':'away_goals'
    }, inplace = True)

In [8]:
df = df[['year','home','away','home_goals','away_goals']]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203956 entries, 0 to 203955
Data columns (total 5 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        203956 non-null  int64
 1   home        203956 non-null  object
 2   away        203956 non-null  object
 3   home_goals  203956 non-null  int64
 4   away_goals  203956 non-null  int64
dtypes: int64(3), object(2)
memory usage: 7.8+ MB

In [9]:
df = df.dropna(how='any',axis=0)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203956 entries, 0 to 203955
Data columns (total 5 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        203956 non-null  int64
 1   home        203956 non-null  object
 2   away        203956 non-null  object
 3   home_goals  203956 non-null  int64
 4   away_goals  203956 non-null  int64
dtypes: int64(3), object(2)
memory usage: 7.8+ MB

In [10]:
print(sorted(df['year'].unique()))
print("#temporadas = ", len(df['year'].unique()))

[1888, 1889, 1890, 1891, 1892, 1893, 1894, 1895, 1896, 1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021]
#temporadas =  123

In [11]:
#temp = ['2017-18', '2018-19', '2019-20', '2020-21', '2021-22', '2022-23']
#df = df.loc[df['year'].isin(temp)].reset_index()

In [12]:
vhome = list(df['home'].unique())
print(len(vhome))

vaway = list(df['away'].unique())
print(len(vaway))

vertice = set(vhome) | set(vaway)
print(len(vertice))
print(list(vertice))

165
165
165
['Swansea City', 'Harrogate Town', 'Swindon Town', 'Middlesbrough Ironopolis', 'Norwich City', 'Bournemouth & Boscombe Athletic', 'Blackpool', 'New Brighton Tower', 'Workington', 'Doncaster Rovers', 'Wolverhampton Wanderers', 'Watford', 'Walsall', 'West Bromwich Albion', 'Macclesfield Town', 'Accrington', 'Clapton Orient', 'Nottingham Forest', 'Arsenal', 'Cheltenham Town', 'Rushden & Diamonds', 'Stoke', 'Reading', 'Swansea Town', 'Gateshead', 'Scunthorpe & Lindsey United', 'Northwich Victoria', 'Aldershot', 'Bolton Wanderers', 'Leeds City', 'Shrewsbury Town', 'Torquay United', 'Barnet', 'Brentford', 'South Shields', 'Yeovil Town', 'Burton Wanderers', 'Queens Park Rangers', 'The Wednesday', 'Rotherham United', 'Barnsley', 'Charlton Athletic', 'Birmingham', 'Small Heath', 'Newcastle United', 'Wigan Athletic', 'Crystal Palace', 'Thames', 'Leicester Fosse', 'Hull City', 'Halifax Town', 'Milton Keynes Dons', 'Walsall Town Swifts', 'Chester City', 'Fulham', 'Chesterfield', 'Merthyr Town', 'Wrexham', 'Dagenham & Redbridge', 'Liverpool', 'Peterborough United', 'Hereford United', 'Stalybridge Celtic', 'Cambridge United', 'Plymouth Argyle', 'West Ham United', 'Brighton & Hove Albion', 'Glossop', 'Sutton United', 'Mansfield Town', 'Grimsby Town', 'Salford City', 'Manchester United', 'Southampton', 'Exeter City', 'Fleetwood Town', 'Bradford City', 'Crewe Alexandra', 'Newton Heath', 'Colchester United', 'Burton Swifts', 'Portsmouth', 'Rochdale', 'Bradford Park Avenue', 'Gainsborough Trinity', 'Notts County', 'Bury', 'Ardwick', 'Accrington Stanley', 'Scarborough', 'New Brighton', 'Hartlepool United', 'Sheffield Wednesday', 'Oldham Athletic', 'Ashington', 'Sunderland', 'Aldershot Town', 'Preston North End', 'Rotherham Town', 'Manchester City', 'Leeds United', 'Scunthorpe United', 'Newport County', 'Hartlepools United', 'Nelson', 'Middlesbrough', 'Rotherham County', 'Burslem Port Vale', 'Tottenham Hotspur', 'Orient', 'Derby County', 'Boston United', 'Northampton Town', 'Luton Town', 'Glossop North End', 'Birmingham City', 'Carlisle United', 'Stoke City', 'Chesterfield Town', 'Coventry City', 'Blackburn Rovers', 'Bristol Rovers', 'Southend United', 'Sheffield United', 'Bournemouth', 'Bristol City', 'Maidstone United', 'Darwen', 'Forest Green Rovers', 'Wigan Borough', 'Aberdare Athletic', 'Woolwich Arsenal', 'Stockport County', 'Leyton Orient', 'Crawley Town', 'Wycombe Wanderers', 'Loughborough', 'Cardiff City', 'York City', 'Burnley', 'Port Vale', 'Burton Albion', 'Southport', 'Bootle', 'Barrow', 'Gillingham', 'Aston Villa', 'Durham City', 'Burton United', 'Morecambe', 'Lincoln City', 'Darlington', 'Kidderminster Harriers', 'Ipswich Town', 'Everton', 'Millwall', 'Huddersfield Town', 'Chelsea', 'Tranmere Rovers', 'Chester', 'Hartlepool', 'Stevenage', 'Wimbledon', 'Oxford United', 'Leicester City']

In [15]:
df['home_win'] = 0.0
df['away_win'] = 0.0
df['draw'] = 0.0

df.loc[df['home_goals'] > df['away_goals'], 'home_win'] = 1.0
df.loc[df['home_goals'] < df['away_goals'], 'away_win'] = 1.0
df.loc[df['home_goals'] == df['away_goals'], 'draw'] = 1.0

df.head(20)

,year,home,away,home_goals,away_goals,home_win,away_win,draw
0,1888,Accrington,Aston Villa,1,1,0.0,0.0,1.0
1,1888,Accrington,Blackburn Rovers,0,2,0.0,1.0,0.0
2,1888,Accrington,Bolton Wanderers,2,3,0.0,1.0,0.0
3,1888,Accrington,Burnley,5,1,1.0,0.0,0.0
4,1888,Accrington,Derby County,6,2,1.0,0.0,0.0
5,1888,Accrington,Everton,3,1,1.0,0.0,0.0
6,1888,Accrington,Notts County,1,2,0.0,1.0,0.0
7,1888,Accrington,Preston North End,0,0,0.0,0.0,1.0
8,1888,Accrington,Stoke,2,0,1.0,0.0,0.0
9,1888,Accrington,West Bromwich Albion,2,1,1.0,0.0,0.0
10,1888,Accrington,Wolverhampton Wanderers,4,4,0.0,0.0,1.0
11,1888,Aston Villa,Accrington,4,3,1.0,0.0,0.0
12,1888,Aston Villa,Blackburn Rovers,6,1,1.0,0.0,0.0
13,1888,Aston Villa,Bolton Wanderers,6,2,1.0,0.0,0.0
14,1888,Aston Villa,Burnley,4,2,1.0,0.0,0.0
15,1888,Aston Villa,Derby County,4,2,1.0,0.0,0.0
16,1888,Aston Villa,Everton,2,1,1.0,0.0,0.0
17,1888,Aston Villa,Notts County,9,1,1.0,0.0,0.0
18,1888,Aston Villa,Preston North End,0,2,0.0,1.0,0.0
19,1888,Aston Villa,Stoke,5,1,1.0,0.0,0.0

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203956 entries, 0 to 203955
Data columns (total 8 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        203956 non-null  int64
 1   home        203956 non-null  object
 2   away        203956 non-null  object
 3   home_goals  203956 non-null  int64
 4   away_goals  203956 non-null  int64
 5   home_win    203956 non-null  float64
 6   away_win    203956 non-null  float64
 7   draw        203956 non-null  float64
dtypes: float64(3), int64(3), object(2)
memory usage: 12.4+ MB

In [17]:
df2 = df.groupby(
    ['home', 'away'],
    as_index=False,
    sort=False).agg({'home_goals':'sum', 'away_goals':'sum', 'home_win':'sum', 'away_win':'sum', 'draw' : 'sum'})

df2.head(20)

,home,away,home_goals,away_goals,home_win,away_win,draw
0,Accrington,Aston Villa,10,9,2.0,1.0,2.0
1,Accrington,Blackburn Rovers,4,9,1.0,2.0,2.0
2,Accrington,Bolton Wanderers,8,9,2.0,2.0,1.0
3,Accrington,Burnley,9,8,2.0,1.0,2.0
4,Accrington,Derby County,17,7,3.0,1.0,1.0
5,Accrington,Everton,10,10,2.0,2.0,1.0
6,Accrington,Notts County,11,14,3.0,2.0,0.0
7,Accrington,Preston North End,5,10,0.0,3.0,2.0
8,Accrington,Stoke,12,3,4.0,0.0,0.0
9,Accrington,West Bromwich Albion,12,7,4.0,0.0,1.0
10,Accrington,Wolverhampton Wanderers,18,11,3.0,1.0,1.0
11,Aston Villa,Accrington,26,12,4.0,1.0,0.0
12,Aston Villa,Blackburn Rovers,163,100,45.0,17.0,18.0
13,Aston Villa,Bolton Wanderers,166,97,42.0,17.0,19.0
14,Aston Villa,Burnley,117,53,29.0,8.0,15.0
15,Aston Villa,Derby County,151,62,42.0,9.0,11.0
16,Aston Villa,Everton,191,137,50.0,28.0,26.0
17,Aston Villa,Notts County,83,29,23.0,3.0,7.0
18,Aston Villa,Preston North End,114,50,37.0,9.0,6.0
19,Aston Villa,Stoke,62,13,17.0,0.0,2.0

In [18]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14217 entries, 0 to 14216
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   home        14217 non-null  object
 1   away        14217 non-null  object
 2   home_goals  14217 non-null  int64
 3   away_goals  14217 non-null  int64
 4   home_win    14217 non-null  float64
 5   away_win    14217 non-null  float64
 6   draw        14217 non-null  float64
dtypes: float64(3), int64(2), object(2)
memory usage: 777.6+ KB

In [21]:
lista = []
for keys, infos in df2.iterrows():
    time1 = infos.home
    time2 = infos.away
    t = df2.loc[(df2['home'] == time2) & (df2['away'] == time1)][['home','away']]
    
    if len(t) == 0:
        lista.append(time1)
        print(time2,"x",time1)

print(len(lista))

Wigan Borough x Chester
Tranmere Rovers x Fleetwood Town
Plymouth Argyle x Forest Green Rovers
3

In [22]:
time1 = "Wigan Borough"
time2 = "Chester"

t = df2.loc[(df2['home'] == time1) & (df2['away'] == time2)][['home','away','home_goals','away_goals','home_win', 'away_win', 'draw']]
print(t.values)

t = df2.loc[(df2['home'] == time2) & (df2['away'] == time1)][['home','away','home_goals','away_goals','home_win', 'away_win', 'draw']]
print(t.values)

[]
[['Chester' 'Wigan Borough' 4 0 1.0 0.0 0.0]]

In [23]:
df2.head(20)

,home,away,home_goals,away_goals,home_win,away_win,draw
0,Accrington,Aston Villa,10,9,2.0,1.0,2.0
1,Accrington,Blackburn Rovers,4,9,1.0,2.0,2.0
2,Accrington,Bolton Wanderers,8,9,2.0,2.0,1.0
3,Accrington,Burnley,9,8,2.0,1.0,2.0
4,Accrington,Derby County,17,7,3.0,1.0,1.0
5,Accrington,Everton,10,10,2.0,2.0,1.0
6,Accrington,Notts County,11,14,3.0,2.0,0.0
7,Accrington,Preston North End,5,10,0.0,3.0,2.0
8,Accrington,Stoke,12,3,4.0,0.0,0.0
9,Accrington,West Bromwich Albion,12,7,4.0,0.0,1.0
10,Accrington,Wolverhampton Wanderers,18,11,3.0,1.0,1.0
11,Aston Villa,Accrington,26,12,4.0,1.0,0.0
12,Aston Villa,Blackburn Rovers,163,100,45.0,17.0,18.0
13,Aston Villa,Bolton Wanderers,166,97,42.0,17.0,19.0
14,Aston Villa,Burnley,117,53,29.0,8.0,15.0
15,Aston Villa,Derby County,151,62,42.0,9.0,11.0
16,Aston Villa,Everton,191,137,50.0,28.0,26.0
17,Aston Villa,Notts County,83,29,23.0,3.0,7.0
18,Aston Villa,Preston North End,114,50,37.0,9.0,6.0
19,Aston Villa,Stoke,62,13,17.0,0.0,2.0

In [24]:
df2.tail(20)

,home,away,home_goals,away_goals,home_win,away_win,draw
14197,Sutton United,Harrogate Town,1,0,1.0,0.0,0.0
14198,Sutton United,Hartlepool United,1,0,1.0,0.0,0.0
14199,Sutton United,Leyton Orient,1,0,1.0,0.0,0.0
14200,Sutton United,Mansfield Town,2,0,1.0,0.0,0.0
14201,Sutton United,Newport County,1,0,1.0,0.0,0.0
14202,Sutton United,Northampton Town,0,0,0.0,0.0,1.0
14203,Sutton United,Oldham Athletic,1,2,0.0,1.0,0.0
14204,Sutton United,Port Vale,4,3,1.0,0.0,0.0
14205,Sutton United,Rochdale,3,0,1.0,0.0,0.0
14206,Sutton United,Salford City,0,0,0.0,0.0,1.0
14207,Sutton United,Scunthorpe United,4,1,1.0,0.0,0.0
14208,Sutton United,Stevenage,2,1,1.0,0.0,0.0
14209,Sutton United,Swindon Town,1,2,0.0,1.0,0.0
14210,Sutton United,Tranmere Rovers,1,1,0.0,0.0,1.0
14211,Sutton United,Walsall,0,1,0.0,1.0,0.0
14212,Swindon Town,Harrogate Town,1,1,0.0,0.0,1.0
14213,Swindon Town,Salford City,1,2,0.0,1.0,0.0
14214,Swindon Town,Sutton United,2,1,1.0,0.0,0.0
14215,Tranmere Rovers,Sutton United,0,1,0.0,1.0,0.0
14216,Walsall,Sutton United,1,0,1.0,0.0,0.0

In [25]:
df2["weight1"] = 0.0
df2["weight2"] = 0.0

In [26]:
for keys, infos in df2.iterrows():
    time1 = infos.home
    time2 = infos.away

    t1 =  df2.loc[(df2['home'] == time1) & (df2['away'] == time2)][['away_goals','away_win','draw']].values
    t2 =  df2.loc[(df2['away'] == time1) & (df2['home'] == time2)][['home_goals','home_win','draw']].values

    g1 = p1 = 0
    for i1 in t1:
        g1 = i1[0]
        p1 = 3*i1[1] + 1*i1[2]

    g2 = p2 = 0
    for i2 in t2:
        g2 = i2[0]
        p2 = 3*i2[1] + 1*i2[2]

    df2.loc[keys,'weight1'] = g1 + g2
    df2.loc[keys,'weight2'] = p1 + p2

In [27]:
df2.head(20)

,home,away,home_goals,away_goals,home_win,away_win,draw,weight1,weight2
0,Accrington,Aston Villa,10,9,2.0,1.0,2.0,35.0,17.0
1,Accrington,Blackburn Rovers,4,9,1.0,2.0,2.0,22.0,15.0
2,Accrington,Bolton Wanderers,8,9,2.0,2.0,1.0,29.0,16.0
3,Accrington,Burnley,9,8,2.0,1.0,2.0,17.0,13.0
4,Accrington,Derby County,17,7,3.0,1.0,1.0,17.0,9.0
5,Accrington,Everton,10,10,2.0,2.0,1.0,21.0,18.0
6,Accrington,Notts County,11,14,3.0,2.0,0.0,36.0,19.0
7,Accrington,Preston North End,5,10,0.0,3.0,2.0,20.0,22.0
8,Accrington,Stoke,12,3,4.0,0.0,0.0,17.0,7.0
9,Accrington,West Bromwich Albion,12,7,4.0,0.0,1.0,25.0,14.0
10,Accrington,Wolverhampton Wanderers,18,11,3.0,1.0,1.0,30.0,19.0
11,Aston Villa,Accrington,26,12,4.0,1.0,0.0,22.0,11.0
12,Aston Villa,Blackburn Rovers,163,100,45.0,17.0,18.0,259.0,211.0
13,Aston Villa,Bolton Wanderers,166,97,42.0,17.0,19.0,240.0,205.0
14,Aston Villa,Burnley,117,53,29.0,8.0,15.0,173.0,136.0
15,Aston Villa,Derby County,151,62,42.0,9.0,11.0,162.0,137.0
16,Aston Villa,Everton,191,137,50.0,28.0,26.0,323.0,283.0
17,Aston Villa,Notts County,83,29,23.0,3.0,7.0,81.0,63.0
18,Aston Villa,Preston North End,114,50,37.0,9.0,6.0,143.0,123.0
19,Aston Villa,Stoke,62,13,17.0,0.0,2.0,34.0,23.0

In [28]:
df2.tail(20)

,home,away,home_goals,away_goals,home_win,away_win,draw,weight1,weight2
14197,Sutton United,Harrogate Town,1,0,1.0,0.0,0.0,0.0,0.0
14198,Sutton United,Hartlepool United,1,0,1.0,0.0,0.0,1.0,1.0
14199,Sutton United,Leyton Orient,1,0,1.0,0.0,0.0,4.0,3.0
14200,Sutton United,Mansfield Town,2,0,1.0,0.0,0.0,2.0,0.0
14201,Sutton United,Newport County,1,0,1.0,0.0,0.0,3.0,3.0
14202,Sutton United,Northampton Town,0,0,0.0,0.0,1.0,0.0,1.0
14203,Sutton United,Oldham Athletic,1,2,0.0,1.0,0.0,3.0,3.0
14204,Sutton United,Port Vale,4,3,1.0,0.0,0.0,5.0,3.0
14205,Sutton United,Rochdale,3,0,1.0,0.0,0.0,3.0,3.0
14206,Sutton United,Salford City,0,0,0.0,0.0,1.0,0.0,2.0
14207,Sutton United,Scunthorpe United,4,1,1.0,0.0,0.0,2.0,1.0
14208,Sutton United,Stevenage,2,1,1.0,0.0,0.0,4.0,1.0
14209,Sutton United,Swindon Town,1,2,0.0,1.0,0.0,4.0,6.0
14210,Sutton United,Tranmere Rovers,1,1,0.0,0.0,1.0,1.0,1.0
14211,Sutton United,Walsall,0,1,0.0,1.0,0.0,2.0,6.0
14212,Swindon Town,Harrogate Town,1,1,0.0,0.0,1.0,2.0,1.0
14213,Swindon Town,Salford City,1,2,0.0,1.0,0.0,4.0,3.0
14214,Swindon Town,Sutton United,2,1,1.0,0.0,0.0,2.0,0.0
14215,Tranmere Rovers,Sutton United,0,1,0.0,1.0,0.0,2.0,4.0
14216,Walsall,Sutton United,1,0,1.0,0.0,0.0,0.0,0.0

In [29]:
for keys, infos in df2.iterrows():
    time1 = infos.home
    time2 = infos.away

    t2 = df2.loc[(df2['home'] == time2) & (df2['away'] == time1)]
    
    if len(t2) == 0:
        t1 =  df2.loc[(df2['home'] == time1) & (df2['away'] == time2)][['home_goals','home_win','draw']].values

        w1 = w2 = 0
        for i1 in t1:
            w1 = i1[0]
            w2 = 3*i1[1] + 1*i1[2]

        new = [time2, time1,np.nan,np.nan,0,0,0,w1,w2]

        new = pd.DataFrame(columns=df2.columns, data=[new])
        
        df2 = pd.concat([df2, new], axis=0)

In [30]:
df2.head(20)

,home,away,home_goals,away_goals,home_win,away_win,draw,weight1,weight2
0,Accrington,Aston Villa,10.0,9.0,2.0,1.0,2.0,35.0,17.0
1,Accrington,Blackburn Rovers,4.0,9.0,1.0,2.0,2.0,22.0,15.0
2,Accrington,Bolton Wanderers,8.0,9.0,2.0,2.0,1.0,29.0,16.0
3,Accrington,Burnley,9.0,8.0,2.0,1.0,2.0,17.0,13.0
4,Accrington,Derby County,17.0,7.0,3.0,1.0,1.0,17.0,9.0
5,Accrington,Everton,10.0,10.0,2.0,2.0,1.0,21.0,18.0
6,Accrington,Notts County,11.0,14.0,3.0,2.0,0.0,36.0,19.0
7,Accrington,Preston North End,5.0,10.0,0.0,3.0,2.0,20.0,22.0
8,Accrington,Stoke,12.0,3.0,4.0,0.0,0.0,17.0,7.0
9,Accrington,West Bromwich Albion,12.0,7.0,4.0,0.0,1.0,25.0,14.0
10,Accrington,Wolverhampton Wanderers,18.0,11.0,3.0,1.0,1.0,30.0,19.0
11,Aston Villa,Accrington,26.0,12.0,4.0,1.0,0.0,22.0,11.0
12,Aston Villa,Blackburn Rovers,163.0,100.0,45.0,17.0,18.0,259.0,211.0
13,Aston Villa,Bolton Wanderers,166.0,97.0,42.0,17.0,19.0,240.0,205.0
14,Aston Villa,Burnley,117.0,53.0,29.0,8.0,15.0,173.0,136.0
15,Aston Villa,Derby County,151.0,62.0,42.0,9.0,11.0,162.0,137.0
16,Aston Villa,Everton,191.0,137.0,50.0,28.0,26.0,323.0,283.0
17,Aston Villa,Notts County,83.0,29.0,23.0,3.0,7.0,81.0,63.0
18,Aston Villa,Preston North End,114.0,50.0,37.0,9.0,6.0,143.0,123.0
19,Aston Villa,Stoke,62.0,13.0,17.0,0.0,2.0,34.0,23.0

In [31]:
df2.tail(20)

,home,away,home_goals,away_goals,home_win,away_win,draw,weight1,weight2
14200,Sutton United,Mansfield Town,2.0,0.0,1.0,0.0,0.0,2.0,0.0
14201,Sutton United,Newport County,1.0,0.0,1.0,0.0,0.0,3.0,3.0
14202,Sutton United,Northampton Town,0.0,0.0,0.0,0.0,1.0,0.0,1.0
14203,Sutton United,Oldham Athletic,1.0,2.0,0.0,1.0,0.0,3.0,3.0
14204,Sutton United,Port Vale,4.0,3.0,1.0,0.0,0.0,5.0,3.0
14205,Sutton United,Rochdale,3.0,0.0,1.0,0.0,0.0,3.0,3.0
14206,Sutton United,Salford City,0.0,0.0,0.0,0.0,1.0,0.0,2.0
14207,Sutton United,Scunthorpe United,4.0,1.0,1.0,0.0,0.0,2.0,1.0
14208,Sutton United,Stevenage,2.0,1.0,1.0,0.0,0.0,4.0,1.0
14209,Sutton United,Swindon Town,1.0,2.0,0.0,1.0,0.0,4.0,6.0
14210,Sutton United,Tranmere Rovers,1.0,1.0,0.0,0.0,1.0,1.0,1.0
14211,Sutton United,Walsall,0.0,1.0,0.0,1.0,0.0,2.0,6.0
14212,Swindon Town,Harrogate Town,1.0,1.0,0.0,0.0,1.0,2.0,1.0
14213,Swindon Town,Salford City,1.0,2.0,0.0,1.0,0.0,4.0,3.0
14214,Swindon Town,Sutton United,2.0,1.0,1.0,0.0,0.0,2.0,0.0
14215,Tranmere Rovers,Sutton United,0.0,1.0,0.0,1.0,0.0,2.0,4.0
14216,Walsall,Sutton United,1.0,0.0,1.0,0.0,0.0,0.0,0.0
0,Wigan Borough,Chester,NaN,NaN,0.0,0.0,0.0,4.0,3.0
0,Tranmere Rovers,Fleetwood Town,NaN,NaN,0.0,0.0,0.0,2.0,3.0
0,Plymouth Argyle,Forest Green Rovers,NaN,NaN,0.0,0.0,0.0,0.0,0.0

In [32]:
time1 = "Wigan Borough"
time2 = "Chester"

t = df2.loc[(df2['home'] == time1) & (df2['away'] == time2)][['home','away','home_goals','away_goals','home_win', 'away_win', 'draw','weight1','weight2']]
print(t.values)

t = df2.loc[(df2['home'] == time2) & (df2['away'] == time1)][['home','away','home_goals','away_goals','home_win', 'away_win', 'draw','weight1','weight2']]
print(t.values)

[['Wigan Borough' 'Chester' nan nan 0.0 0.0 0.0 4.0 3.0]]
[['Chester' 'Wigan Borough' 4.0 0.0 1.0 0.0 0.0 0.0 0.0]]

In [33]:
df3 = df2[['home','away','weight1','weight2']]

df3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14220 entries, 0 to 0
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   home     14220 non-null  object
 1   away     14220 non-null  object
 2   weight1  14220 non-null  float64
 3   weight2  14220 non-null  float64
dtypes: float64(2), object(2)
memory usage: 555.5+ KB

In [34]:
df3.head(20)

           home                     away  weight1  weight2
0    Accrington              Aston Villa     35.0     17.0
1    Accrington         Blackburn Rovers     22.0     15.0
2    Accrington         Bolton Wanderers     29.0     16.0
3    Accrington                  Burnley     17.0     13.0
4    Accrington             Derby County     17.0      9.0
5    Accrington                  Everton     21.0     18.0
6    Accrington             Notts County     36.0     19.0
7    Accrington        Preston North End     20.0     22.0
8    Accrington                    Stoke     17.0      7.0
9    Accrington     West Bromwich Albion     25.0     14.0
10   Accrington  Wolverhampton Wanderers     30.0     19.0
11  Aston Villa               Accrington     22.0     11.0
12  Aston Villa         Blackburn Rovers    259.0    211.0
13  Aston Villa         Bolton Wanderers    240.0    205.0
14  Aston Villa                  Burnley    173.0    136.0
15  Aston Villa             Derby County    162.0    137.0
16  Aston Villa                  Everton    323.0    283.0
17  Aston Villa             Notts County     81.0     63.0
18  Aston Villa        Preston North End    143.0    123.0
19  Aston Villa                    Stoke     34.0     23.0

In [35]:
df3.tail(20)

                  home                 away  weight1  weight2
14200    Sutton United       Mansfield Town      2.0      0.0
14201    Sutton United       Newport County      3.0      3.0
14202    Sutton United     Northampton Town      0.0      1.0
14203    Sutton United      Oldham Athletic      3.0      3.0
14204    Sutton United            Port Vale      5.0      3.0
14205    Sutton United             Rochdale      3.0      3.0
14206    Sutton United         Salford City      0.0      2.0
14207    Sutton United    Scunthorpe United      2.0      1.0
14208    Sutton United            Stevenage      4.0      1.0
14209    Sutton United         Swindon Town      4.0      6.0
14210    Sutton United      Tranmere Rovers      1.0      1.0
14211    Sutton United              Walsall      2.0      6.0
14212     Swindon Town       Harrogate Town      2.0      1.0
14213     Swindon Town         Salford City      4.0      3.0
14214     Swindon Town        Sutton United      2.0      0.0
14215  Tranmere Rovers        Sutton United      2.0      4.0
14216          Walsall        Sutton United      0.0      0.0
0        Wigan Borough              Chester      4.0      3.0
0      Tranmere Rovers       Fleetwood Town      2.0      3.0
0      Plymouth Argyle  Forest Green Rovers      0.0      0.0

In [36]:
df3.to_csv('../data/work1/englishfootball_1888_2023.csv', index=False, sep=';')